export const projects = [
  {
    title: 'TrackMania Website',
    description: "This project is a webpage presenting my favourite series of games from children - 'TrackMania'. By navigating through all the page you can see different versions of the game with their descriptions.",
      image: '/images/TM.png',
      tags: ['JavaScript', 'Bootstrap', 'Sass'],
    source: 'https://macieytm.github.io/TrackMania-Website',
    visit: 'https://github.com/MacieyTM/TrackMania-Website',
    id: 0,
  },
  {
    title: 'Weather App',
    description:"Since the weather on Earth is doubtful, I decided to create an application where you can check the temperature, the humidity and the type of weather (Rain, Snow, Sun, Storm, Clouds, etc.) of EVERY city / country / geographic land.",
    image: '/images/Weather.png',
    tags: ['JavaScript', 'API'],
    source: 'https://macieytm.github.io/Weather-App',
    visit: 'https://github.com/MacieyTM/Weather-App',
    id: 1,
  },
  {
    title: 'Exchange Rate',
    description: "Have you ever wanted to check how much PLN is EURO quickly? This is just one of the many features that my application has to offer. There is a friendly interface which allows you to navigate through different currency to receive the exact value.",
      image: '/images/Exchange.png',
      tags: ['JavaScript', 'API'],
    source: 'https://macieytm.github.io/Exchange-Rate',
    visit: 'https://github.com/MacieyTM/Exchange-Rate',
    id: 2,
  },
  {
    title: 'My Restaurant',
    description: "This is a prototype of online shop where you can add your products to one 'shopping basket'. In the basket you can add or remove the items. Also, it is a great summary of what and how much you have recently chosen and need to pay overall.",
    image: '/images/MyRestaurant.png',
    tags: ['React', 'Firebase'],
    source: 'https://macieytm.github.io/My-Restaurant-v2',
    visit: 'https://github.com/MacieyTM/My-Restaurant-v2',
    id: 3,
  },
  {
    title: 'Great Quotes',
    description: "What is your favourite quote from films/books/games? Share them with everyone by visiting my web application. You just need to click the button, save your changes and that is it! You are also allowed to see and comment all the other quotes.",
      image: '/images/Quotes.png',
      tags: ['React', 'React-Router', 'Firebase'],
    source: 'https://macieytm.github.io/Best-Quotes',
    visit: 'https://github.com/MacieyTM/Best-Quotes',
    id: 4,
  },
  {
    title: 'Login Authentication',
    description: "Forgetting about logging out is dangerous because anyone can hack your profile. With my application you do not have to worry about that because you will be automatically logged out!",
      image: '/images/LoginAuth.png',
      tags: ['React', 'React-Router', 'Firebase'],
    source: 'https://macieytm.github.io/Login-Authentication',
    visit: 'https://github.com/MacieyTM/Login-Authentication',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Wyróżnienie jako betatester'},
  { year: 2019, text: 'Udział w światowym turnieju gry TrackMania'},
  { year: 2019, text: 'Wolontariusz w POLARIS - OPP'},
  { year: 2020, text: 'Laureat Złotego Indeksu Politechniki Krakowskiej'},
  { year: 2020, text: 'Laureat Złotego Indeksu Politechniki Śląskiej'},
];