export const projects = [
  {
    title: 'TrackMania Website',
    description: "This project is a webpage presenting my favourite series of games from children - 'TrackMania'. By navigating through all the page you can see different versions of the game with their descriptions.",
      image: '/images/TM.png',
      tags: ['JavaScript', 'Bootstrap', 'Sass'],
    source: 'https://macieytm.github.io/TrackMania-Website',
    visit: 'https://github.com/MacieyTM/TrackMania-Website',
    id: 0,
  },
  {
    title: 'Weather App',
    description:"Since the weather on Earth is doubtful, I decided to create an application where you can check the temperature, the humidity and the type of weather (Rain, Snow, Sun, Storm, Clouds, etc.) of EVERY city / country / geographic land.",
    image: '/images/Weather.png',
    tags: ['JavaScript', 'API'],
    source: 'https://macieytm.github.io/Weather-App',
    visit: 'https://github.com/MacieyTM/Weather-App',
    id: 1,
  },
  {
    title: 'Exchange Rate',
    description: "Have you ever wanted to check how much PLN is EURO quickly? This is just one of the many features that my application has to offer. There is a friendly interface which allows you to navigate through different currency to receive the exact value.",
      image: '/images/Exchange.png',
      tags: ['JavaScript', 'API'],
    source: 'https://macieytm.github.io/Exchange-Rate',
    visit: 'https://github.com/MacieyTM/Exchange-Rate',
    id: 2,
  },
  {
    title: 'My Restaurant',
    description: "This is a prototype of online shop where you can add your products to one 'shopping basket'. In the basket you can add or remove the items. Also, it is a great summary of what and how much you have recently chosen and need to pay overall.",
    image: '/images/MyRestaurant.png',
    tags: ['React', 'Firebase'],
    source: 'https://macieytm.github.io/My-Restaurant-v2',
    visit: 'https://github.com/MacieyTM/My-Restaurant-v2',
    id: 3,
  },
  {
    title: 'Great Quotes',
    description: "What is your favourite quote from films/books/games? Share them with everyone by visiting my web application. You just need to click the button, save your changes and that is it! You are also allowed to see and comment all the other quotes.",
      image: '/images/Quotes.png',
      tags: ['React', 'React-Router', 'Firebase'],
    source: 'https://macieytm.github.io/Best-Quotes',
    visit: 'https://github.com/MacieyTM/Best-Quotes',
    id: 4,
  },
  {
    title: 'Login Authentication',
    description: "Forgetting about logging out is dangerous because anyone can hack your profile. With my application you do not have to worry about that because you will be automatically logged out!",
      image: '/images/LoginAuth.png',
      tags: ['React', 'React-Router', 'Firebase'],
    source: 'https://macieytm.github.io/Login-Authentication',
    visit: 'https://github.com/MacieyTM/Login-Authentication',
    id: 5,
  },
  {
    title: 'Photo Company',
    description: "I decided to make a website for a photo company presenting their work and members. That company does not exist for real but I just wanted to practice UI/UX skills that I have experienced so far. Might it will be commercial in the future.",
      image: '/images/PhotoCompany.png',
      tags: ['JavaScript', 'Bootstrap'],
    source: 'https://macieytm.github.io/Photo-Company',
    visit: 'https://github.com/MacieyTM/Photo-Company',
    id: 6,
  },
  {
    title: 'Drink Search',
    description: "Would you like to see a list that contains elements which you can filter by letters of their names? If so, I built a project due to this idea. Just type letters and the names will be automatically filtered. It helps when the list is very big.",
      image: '/images/DrinkSearch.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/Drink-Search',
    visit: 'https://github.com/MacieyTM/Drink-Search',
    id: 7,
  },
  {
    title: 'TODO List',
    description: "I know that TODO projects are so popular and not very impressive for employers but I wanted to show you that I can build a pretty functional TODO list anyway. Not only are you able to add the elements but you can also edit and remove them.",
      image: '/images/TODOList.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/TODO-List',
    visit: 'https://github.com/MacieyTM/TODO-List',
    id: 8,
  },
  {
    title: 'Stopwatch App',
    description: "I created a stopwatch application that lets you measure time. It contains functionalities such as: Start, Pause, Stop, Resume, See The Records, Remove All The Records. All is automatically saved in special archive where you can see all times.",
      image: '/images/Stopwatch.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/Stopwatch-App',
    visit: 'https://github.com/MacieyTM/Stopwatch-App',
    id: 9,
  },
  {
    title: 'My Notes',
    description: "A prototype of a notebook with three types: Shopping, Job, Others. When creating a note you can choose a type of the note. It helps to organize everytihng into categories that have own background colour.",
      image: '/images/MyNotes.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/My-Notes',
    visit: 'https://github.com/MacieyTM/My-Notes',
    id: 10,
  },
  {
    title: 'Wallet App',
    description: "This application is a transactions counter. You can enter your expenses and salary. After that, you will see how much money there is left. I would also like to notice that there are two types: light and dark mode.",
      image: '/images/Wallet.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/Wallet-App',
    visit: 'https://github.com/MacieyTM/Wallet-App',
    id: 11,
  },
  {
    title: 'Timer App',
    description: "Would you like to know how much time left to particular date? With my application, it is very easy. Just enter some date and you will see the result! You can also add an image and name of the event that will happen then.",
      image: '/images/Timer.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/Timer-App',
    visit: 'https://github.com/MacieyTM/Timer-App',
    id: 12,
  },
  {
    title: 'Diamond CMS',
    description: "This is a project that I wanted to create to show you my front-end skills. Especially, take a look at this graph. It was created by someone else, not by me. But I placed it in the way that it suits the all application beautifully.",
      image: '/images/DiamondCMS.png',
      tags: ['JavaScript', 'Bootstrap'],
    source: 'https://macieytm.github.io/Diamond-CMS',
    visit: 'https://github.com/MacieyTM/Diamond-CMS',
    id: 13,
  },
  {
    title: 'Expenses Counter',
    description: "This project is a webpage that counts all expenses you add. You can filter them by chosen year. If you have lots of different expenses in one year amongst all months then you can see blue diagrams of each month.",
      image: '/images/ExpensesCounter.png',
      tags: ['JavaScript', 'React'],
    source: 'https://macieytm.github.io/Expenses-Counter',
    visit: 'https://github.com/MacieyTM/Expenses-Counter',
    id: 14,
  },
  {
    title: 'Frost Company',
    description: "An example of a website for a company which make cars. In this project I wanted to focus on good layout. I used Bootstrap to add good styling features to the project. Also, there is a map that shows exact location.",
      image: '/images/FrostCompany.png',
      tags: ['JavaScript', 'Bootstrap'],
    source: 'https://macieytm.github.io/Frost-Company',
    visit: 'https://github.com/MacieyTM/Frost-Company',
    id: 15,
  },
  {
    title: 'Bill Splitter',
    description: "Have you ever had a confusing situation with your friends when you wanted to give a bill in the restaurant but you did not know how much money you should give separately? With my application there is no problem anymore!",
      image: '/images/BillSplitter.png',
      tags: ['JavaScript'],
    source: 'https://macieytm.github.io/Bill-Splitter',
    visit: 'https://github.com/MacieyTM/Bill-Splitter',
    id: 16,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Wyróżnienie jako betatester'},
  { year: 2019, text: 'Udział w światowym turnieju gry TrackMania'},
  { year: 2019, text: 'Wolontariusz w POLARIS - OPP'},
  { year: 2020, text: 'Laureat Złotego Indeksu Politechniki Krakowskiej'},
  { year: 2020, text: 'Laureat Złotego Indeksu Politechniki Śląskiej'},
];
